name = "starprinttalks-api"
main = "src/worker.js"
compatibility_date = "2024-01-15"

# Environment variables
[vars]
CLOUDFLARE_ACCOUNT_ID = "0fcf859333ab748f1f4412f3d496cc99"

# AI Model configuration
[ai]
binding = "AI"
model = "@cf/meta/llama-3-8b-instruct"

# D1 Database
[[d1_databases]]
binding = "starprinttalks_db"
database_name = "starprinttalks-db"
database_id = "0ac09cfb-54c7-48c4-9bce-8e3b2d88af40"