import React from 'react';

export const motion = {
  div: ({ children, ...props }: any) => React.createElement('div', props, children),
  button: ({ children, ...props }: any) => React.createElement('button', props, children),
  span: ({ children, ...props }: any) => React.createElement('span', props, children),
  section: ({ children, ...props }: any) => React.createElement('section', props, children),
  article: ({ children, ...props }: any) => React.createElement('article', props, children),
  header: ({ children, ...props }: any) => React.createElement('header', props, children),
  main: ({ children, ...props }: any) => React.createElement('main', props, children),
  aside: ({ children, ...props }: any) => React.createElement('aside', props, children),
  nav: ({ children, ...props }: any) => React.createElement('nav', props, children),
  ul: ({ children, ...props }: any) => React.createElement('ul', props, children),
  li: ({ children, ...props }: any) => React.createElement('li', props, children),
  h1: ({ children, ...props }: any) => React.createElement('h1', props, children),
  h2: ({ children, ...props }: any) => React.createElement('h2', props, children),
  h3: ({ children, ...props }: any) => React.createElement('h3', props, children),
  h4: ({ children, ...props }: any) => React.createElement('h4', props, children),
  h5: ({ children, ...props }: any) => React.createElement('h5', props, children),
  h6: ({ children, ...props }: any) => React.createElement('h6', props, children),
  p: ({ children, ...props }: any) => React.createElement('p', props, children),
  a: ({ children, ...props }: any) => React.createElement('a', props, children),
  img: ({ ...props }: any) => React.createElement('img', props),
  input: ({ ...props }: any) => React.createElement('input', props),
  textarea: ({ children, ...props }: any) => React.createElement('textarea', props, children),
  form: ({ children, ...props }: any) => React.createElement('form', props, children),
  label: ({ children, ...props }: any) => React.createElement('label', props, children),
  select: ({ children, ...props }: any) => React.createElement('select', props, children),
  option: ({ children, ...props }: any) => React.createElement('option', props, children),
  table: ({ children, ...props }: any) => React.createElement('table', props, children),
  thead: ({ children, ...props }: any) => React.createElement('thead', props, children),
  tbody: ({ children, ...props }: any) => React.createElement('tbody', props, children),
  tr: ({ children, ...props }: any) => React.createElement('tr', props, children),
  td: ({ children, ...props }: any) => React.createElement('td', props, children),
  th: ({ children, ...props }: any) => React.createElement('th', props, children),
};

export const AnimatePresence = ({ children }: any) => children;
